[project]
name = "maplibre-shinylive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "maplibre[shiny]>=0.3.1",
    "shiny>=1.4.0",
    "shinylive>=0.8.3",
]
